# permissions for end users to view failoverstates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: failover-operator
    app.kubernetes.io/managed-by: kustomize
  name: failoverstate-viewer-role
rules:
- apiGroups:
  - failover.cyber-engine.com
  resources:
  - failoverstates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - failover.cyber-engine.com
  resources:
  - failoverstates/status
  verbs:
  - get
