# permissions for end users to edit failoverstates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: failover-operator
    app.kubernetes.io/managed-by: kustomize
  name: failoverstate-editor-role
rules:
- apiGroups:
  - crd.cyber-engine.com
  resources:
  - failoverstates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.cyber-engine.com
  resources:
  - failoverstates/status
  verbs:
  - get
