---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - virtualservices
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.cyber-engine.com
  resources:
  - failoverpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.cyber-engine.com
  resources:
  - failoverpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - crd.cyber-engine.com
  resources:
  - failoverpolicies/status
  verbs:
  - get
  - patch
  - update
