apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: system
type: Opaque
data:
  # These values are base64 encoded and should be replaced with actual credentials
  # Example: echo -n "your-access-key" | base64
  access_key: WW91ckFXU0FjY2Vzc0tleUlE    # Replace with actual base64 encoded AWS access key
  secret_key: WW91ckFXU1NlY3JldEtleQ==     # Replace with actual base64 encoded AWS secret key
  # Optional fields
  region: dXMtd2VzdC0y                     # Replace with actual base64 encoded AWS region (e.g., us-west-2)
  # session_token: WW91ckFXU1Nlc3Npb25Ub2tlbg==  # Uncomment and replace for temporary credentials 