apiVersion: crd.hahomelabs.com/v1alpha1
kind: FailoverPolicy
metadata:
  labels:
    app.kubernetes.io/name: failover-operator
    app.kubernetes.io/managed-by: kustomize
  name: kyverno
  namespace: kyverno
spec:
  desiredState: "primary"
  mode: "safe"
  managedResources:
    - kind: Deployment
      name: kyverno-admission-controller
    - kind: Deployment
      name: kyverno-background-controller
    - kind: Deployment
      name: kyverno-cleanup-controller
    - kind: Deployment
      name: kyverno-reports-controller
    - kind: CronJob
      name: kyverno-cleanup-admission-reports
    - kind: CronJob
      name: kyverno-cleanup-cluster-admission-reports
    - kind: HelmRelease
      name: kyverno
    - kind: Kustomization
      name: infra-policies-stage-1
      namespace: flux-system