apiVersion: crd.hahomelabs.com/v1alpha1
kind: FailoverPolicy
metadata:
  labels:
    app.kubernetes.io/name: failover-operator
    app.kubernetes.io/managed-by: kustomize
  name: wordpress
  namespace: wordpress
spec:
  desiredState: "primary"
  mode: "safe"
  virtualServices: 
    - "wordpress"
  volumeReplications:
    - data-wordpress-mariadb-0
    - wordpress
