apiVersion: crd.hahomelabs.com/v1alpha1
kind: FailoverGroup
metadata:
  name: wordpress-high-availability
  namespace: wordpress
spec:
  # Optional operator identifier
  operatorID: "wordpress-operator"
  
  # Optional flag to disable automatic failovers
  suspended: false
  
  # Optional timeout settings
  timeouts:
    transitoryState: "5m"  # Maximum time in FAILOVER/FAILBACK states
    unhealthyPrimary: "2m" # Time PRIMARY can be unhealthy
    heartbeat: "1m"        # Time without heartbeats before auto-failover
  
  # Optional heartbeat interval
  heartbeatInterval: "30s"

  workloads:
    - kind: StatefulSet
      name: wordpress-mariadb-primary
      volumeReplications:
        - data-wordpress-mariadb-primary-0
  
    - kind: StatefulSet
      name: wordpress-mariadb-secondary
      volumeReplications:
        - data-wordpress-mariadb-secondary-0
        - data-wordpress-mariadb-secondary-1
    
    - kind: StatefulSet
      name: wordpress-memcached
    
    - kind: Deployment
      name: wordpress
      
  networkResources:
    - kind: VirtualService
      name: wordpress
    - kind: Ingress
      name: wordpress-ingress

  fluxResources:
    - kind: HelmRelease
      name: wordpress
      triggerReconcile: true
      
status:
  state: "PRIMARY"
  health: "OK"
  
  lastFailoverTime: "2023-05-15T08:30:00Z"
  
  globalState:
    activeCluster: "us-east-1"
    thisCluster: "us-east-1"
    dbSyncStatus: "Synced"
    lastSyncTime: "2023-05-15T08:45:00Z"
    clusters:
      - name: "us-east-1"
        role: "PRIMARY"
        health: "OK"
        lastHeartbeat: "2023-05-15T08:45:00Z"
      - name: "us-west-2"
        role: "STANDBY"
        health: "OK"
        lastHeartbeat: "2023-05-15T08:44:30Z" 