apiVersion: failover.cyber-engine.com/v1alpha1
kind: FailoverState
metadata:
  labels:
    app.kubernetes.io/name: failover-operator
    app.kubernetes.io/managed-by: kustomize
  name: wordpress
  namespace: wordpress
spec:
  failoverState: "primary"
  virtualServices: 
    - "wordpress"
  volumeReplications:
    - data-wordpress-mariadb-0
    - wordpress
